<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [94]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [95]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['Necesito comprar algunas frutas.', 'espanhol'], ['¿Cuál es tu comida favorita?', 'espanhol'], ['I like listening to music.', 'inglês'], ['Voy al parque todos los días.', 'espanhol'], ['¿Hablas español?', 'espanhol'], ['Vamos a dar un paseo.', 'espanhol'], ["I'm studying for my exams.", 'inglês'], ['Vou viajar para o exterior nas férias.', 'português'], ['Tenho uma reunião importante amanhã.', 'português'], ['I love to read books.', 'inglês'], ['I need to buy some groceries.', 'inglês'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ["I'm learning to play the guitar.", 'inglês'], ["I'm going to the movies tonight.", 'inglês'], ['The weather is nice today.', 'inglês'], ['Vou visitar meus avós no domingo.', 'português'], ['Preciso fazer exercícios físicos regularmente.', 'português'], ['Can you help me with this?', 'inglês'], ["Let's go for a walk.", 'inglês'], ['Gosto de fazer caminhadas na natureza.', 'português'], ['Me encanta leer libros.', 'espanhol'], ['Meu time de futebol favo

O DataFrame do pandas facilita a visualização.

In [96]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0                    Necesito comprar algunas frutas.   espanhol
1                        ¿Cuál es tu comida favorita?   espanhol
2                          I like listening to music.     inglês
3                       Voy al parque todos los días.   espanhol
4                                    ¿Hablas español?   espanhol
5                               Vamos a dar un paseo.   espanhol
6                          I'm studying for my exams.     inglês
7              Vou viajar para o exterior nas férias.  português
8                Tenho uma reunião importante amanhã.  português
9                               I love to read books.     inglês
10                      I need to buy some groceries.     inglês
11                     ¿Cómo estuvo tu fin de semana?   espanhol
12                   I'm learning to play the guitar.     inglês
13                   I'm going to the movies tonight.     inglês
14                         The weather is nice today.     inglês
15                  Vou visitar meus avós no domingo.  português
16     Preciso fazer exercícios físicos regularmente.  português
17                         Can you help me with this?     inglês
18                               Let's go for a walk.     inglês
19             Gosto de fazer caminhadas na natureza.  português
20                            Me encanta leer libros.   espanhol
21        Meu time de futebol favorito ganhou o jogo.  português
22                              How was your weekend?     inglês
23                               The cat is sleeping.     inglês
24                       Preciso comprar leite e pão.  português
25                      Me gustaría ir de vacaciones.   espanhol
26              Adoro passar tempo com minha família.  português
27                   Estoy planeando unas vacaciones.   espanhol
28                           I'm planning a vacation.     inglês
29               O filme que assisti ontem foi ótimo.  português
30                  Estou indo para o trabalho agora.  português
31                         Vamos ao cinema no sábado.  português
32                             A festa começa às 20h.  português
33            ¿Dónde está el restaurante más cercano?   espanhol
34                  Vamos sair para jantar no sábado.  português
35                                 Hola, ¿cómo estás?   espanhol
36      ¿Tienes alguna recomendación de restaurantes?   espanhol
37                 Estou estudando para o vestibular.  português
38                   I'm sorry for the inconvenience.     inglês
39   Do you have any recommendations for restaurants?     inglês
40                                  Have a great day!     inglês
41                            I want to learn French.     inglês
42                  Você já visitou o Rio de Janeiro?  português
43                            I enjoy playing soccer.     inglês
44          O parque fica cheio aos finais de semana.  português
45                       El clima está agradable hoy.   espanhol
46             Estou ansioso para as férias de verão.  português
47                          Quiero aprender italiano.   espanhol
48  Preciso resolver esse problema o mais rápido p...  português
49                  Me gusta cocinar la cena en casa.   espanhol
50                           Ella canta hermosamente.   espanhol
51       Vamos fazer um churrasco no final de semana.  português
52                                   What time is it?     inglês
53                             El perro está jugando.   espanhol
54                         This is a beautiful place.     inglês
55                             Me gusta bailar salsa.   espanhol
56                       I'm excited for the concert.     inglês
57  Estou cansado depois de um longo dia de trabalho.  português
58                 Estoy emocionado por el concierto.   espanhol
59                            Hoje é meu aniversário!  português
60                    ¿Dónde puedo encontrar un taxi?   espanhol
61                   W

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [97]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)

# Características criadas pelo grupo_________________________________________________________________________________________________________________________________________________________________________________________

def presenca_eng(frase):
  eng_only = ["'", "W", "w"]
  if any(sub in frase for sub in eng_only):
    return 1
  else:
    return 0
  
def presenca_por(frase):
  por_only = ["ç", "lh", "nh"]
  if any(sub in frase for sub in por_only):
    return 1
  else:
    return 0
  
def presenca_esp(frase):
  esp_only = ["¿", "¡", "ñ", "ü"]
  if any(sub in frase for sub in esp_only):
    return 1
  else:
    return 0
  
def presenca_y(frase):
  possui_y = ["y"]
  if any(sub in frase for sub in possui_y):
    return 1
  else:
    return 0

def presenca_acento(frase):
  possui_acento =  ['á', 'à', 'ã', 'â', 'é', 'ê', 'í', 'ó', 'ô', 'õ', 'ú', 'ç', 'ü', 'ñ']
  if any(sub in frase for sub in possui_acento):
    return 1
  else:
    return 0
  
# fim das características criadas pelo grupo________________________________________________________________________________________________________________________________________________________________________________

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=presenca_eng(texto)
  caracteristica3=presenca_por(texto)
  caracteristica4=presenca_esp(texto)
  caracteristica5=presenca_y(texto)
  caracteristica6=presenca_acento(texto)
  
  
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, caracteristica5, caracteristica6, frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

#dados = pd.DataFrame(padroes)
#dados

df = pd.DataFrame(padroes)

# Configurar o Pandas para mostrar todas as linhas
pd.set_option('display.max_rows', None)

# Mostrar o DataFrame completo
print(df.to_string(index=False))


[[7.0, 0, 0, 0, 0, 0, 'espanhol'], [4.4, 0, 0, 0, 0, 1, 'espanhol'], [4.2, 0, 0, 0, 0, 0, 'inglês'], [3.8333333333333335, 0, 0, 0, 1, 1, 'espanhol'], [6.5, 0, 0, 1, 0, 1, 'espanhol'], [3.2, 0, 0, 0, 0, 0, 'espanhol'], [3.3333333333333335, 0, 0, 0, 1, 0, 'inglês'], [4.428571428571429, 0, 0, 0, 0, 1, 'português'], [6.2, 0, 1, 0, 0, 1, 'português'], [3.2, 0, 0, 0, 0, 0, 'inglês'], [3.8333333333333335, 0, 0, 0, 1, 0, 'inglês'], [3.8333333333333335, 0, 0, 0, 0, 1, 'espanhol'], [3.5714285714285716, 0, 0, 0, 1, 0, 'inglês'], [3.5714285714285716, 0, 0, 0, 0, 0, 'inglês'], [4.2, 1, 0, 0, 1, 0, 'inglês'], [4.5, 0, 0, 0, 0, 1, 'português'], [8.2, 0, 0, 0, 0, 1, 'português'], [3.3333333333333335, 1, 0, 0, 1, 0, 'inglês'], [2.3333333333333335, 1, 0, 0, 0, 0, 'inglês'], [5.333333333333333, 0, 1, 0, 0, 0, 'português'], [4.75, 0, 0, 0, 0, 0, 'espanhol'], [4.375, 0, 1, 0, 0, 0, 'português'], [4.25, 1, 0, 0, 1, 0, 'inglês'], [4.0, 0, 0, 0, 0, 0, 'inglês'], [4.6, 0, 0, 0, 0, 1, 'português'], [4.8, 0, 0, 

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:56: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:56: SyntaxWarning: invalid escape sequence '\w'
C:\Users\marog\AppData\Local\Temp\ipykernel_3856\4057193321.py:5: SyntaxWarning: invalid escape sequence '\s'
  palavras = re.split("\s",texto)
C:\Users\marog\AppData\Local\Temp\ipykernel_3856\4057193321.py:56: SyntaxWarning: invalid escape sequence '\w'
  pattern_regex = re.compile('[^\w+]', re.UNICODE)


<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [98]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [99]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 79.71%
[[10  4  9]
 [ 0 21  1]
 [ 0  0 24]]
              precision    recall  f1-score   support

    espanhol       1.00      0.43      0.61        23
      inglês       0.84      0.95      0.89        22
   português       0.71      1.00      0.83        24

    accuracy                           0.80        69
   macro avg       0.85      0.80      0.78        69
weighted avg       0.85      0.80      0.77        69

métricas mais confiáveis
[[2 1 4]
 [2 4 2]
 [1 0 7]]
              precision    recall  f1-score   support

    espanhol       0.40      0.29      0.33         7
      inglês       0.80      0.50      0.62         8
   português       0.54      0.88      0.67         8

    accuracy                           0.57        23
   macro avg       0.58      0.55      0.54        23
weighted avg       0.59      0.57      0.55        23

