<a href="https://colab.research.google.com/github/MarogobaCTD/UFPR/blob/main/arq_dados_atividade1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [2]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [3]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['Necesito comprar algunas frutas.', 'espanhol'], ['Hola, ¿cómo estás?', 'espanhol'], ["Let's go for a walk.", 'inglês'], ['¿Hablas español?', 'espanhol'], ['Vamos a dar un paseo.', 'espanhol'], ["I'm learning to play the guitar.", 'inglês'], ['Me gusta cocinar la cena en casa.', 'espanhol'], ['¿Puedes ayudarme con esto?', 'espanhol'], ['Gosto de praticar esportes ao ar livre.', 'português'], ['Where is the nearest restaurant?', 'inglês'], ['El perro está jugando.', 'espanhol'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ['¡Que tengas un buen día!', 'espanhol'], ['O filme que assisti ontem foi ótimo.', 'português'], ['Can you help me with this?', 'inglês'], ['Estoy aprendiendo a tocar el piano.', 'espanhol'], ['I enjoy playing soccer.', 'inglês'], ['Vamos ao cinema no sábado.', 'português'], ['Vou viajar para o exterior nas férias.', 'português'], ['Do you speak English?', 'inglês'], ['Quero aprender a tocar violão.', 'português'], ['I have a meeting at 2 PM.', 'inglês'], ['O res

O DataFrame do pandas facilita a visualização.

In [4]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0            Necesito comprar algunas frutas.   espanhol
1                          Hola, ¿cómo estás?   espanhol
2                        Let's go for a walk.     inglês
3                            ¿Hablas español?   espanhol
4                       Vamos a dar un paseo.   espanhol
..                                        ...        ...
87          Vou visitar meus avós no domingo.  português
88      Adoro passar tempo com minha família.  português
89                              ¿Qué hora es?   espanhol
90          Estou indo para o trabalho agora.  português
91  Estou aprendendo a cozinhar pratos novos.  português

[92 rows x 2 columns]

In [104]:
import re

def regra_1(frase):

  # 1. Verificar presença de verbos no presente do indicativo
  verbos_presente = re.findall(r"\w*\[ando|indo|iendo|amos|áis|ão|an|en|mos|is|em|ém|er|ar|ou|ir]", frase)
  print(verbos_presente)
  print(frase.split())
  probabilidade_verbo = len(verbos_presente) / len(frase.split())  # Proporção de verbos no presente
  print(probabilidade_verbo)

  # 2. Verificar presença de letras ou símbolos
  presenca_es = "".join(["ñ", "¿", "¡"]) in frase
  presenca_usa = "".join(["'","I", "the", "The"]) in frase

  # 3. Calcular a probabilidade combinada
  if (probabilidade_verbo > 0.25 and not presenca_es and presenca_usa):
      probabilidade = 0.75  # Alta probabilidade
  elif (probabilidade_verbo > 0.15 and presenca_es):
      probabilidade = 0.5  # Média probabilidade
  else:
      probabilidade = 0.25  # Baixa probabilidade

  return probabilidade_verbo + probabilidade

# Exemplos de uso
#frase_portuguesa = "Estamos indo para a praia agora e ela também."
#frase_espanhola = "Me gusta comer pizza en la playa e Hablar español."

#prob_pt = regra_1(frase_portuguesa)
#prob_es = regra_1(frase_espanhola)

#print(f"{frase_portuguesa} - Probabilidade: {prob_pt:.2f}")
#print(f"{frase_espanhola} - Probabilidade: {prob_es:.2f}")

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [105]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

from unicodedata import category

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)

def extrair_consoantes(frase):
  consoantes = re.findall(r'[¡¿ñÑ]+', frase)
  letras = ''.join(consoantes)
  #print(letras)
  return len(letras)

def conta_palavras_acento(text):
  # Palavras com acento
  accent_regex = re.compile(r"\w+[\xe0-\xff]")

  # Localiza no texto as palavras
  words = re.findall(r"\w+", text)

  # Iterate over the words and return the first one with an accent.
  count = 0
  for word in words:
    if accent_regex.match(word):
      count += 1

  return count

def mediaPalavrasAcentudas(frase):
  qtdPalavras = len(re.split("\s",frase))
  acentoPalavras = conta_palavras_acento(frase)
  valor = acentoPalavras/qtdPalavras
  #print(valor)
  return valor

def funcao2(frase):
  return 0
#
#   crie suas funções aqui
#
#

def localizar_numero(frase):
  for caractere in frase:
      if caractere.isdigit():
        return 0
  return 1

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=regra_1(texto)
  caracteristica3=funcao2(texto)
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

['ar']
['Necesito', 'comprar', 'algunas', 'frutas']
0.25
[]
['Hola', 'cómo', 'estás']
0.0
[]
['Let', 's', 'go', 'for', 'a', 'walk']
0.0
[]
['Hablas', 'español']
0.0
['amos', 'ar']
['Vamos', 'a', 'dar', 'un', 'paseo']
0.4
['ar', 'ar']
['I', 'm', 'learning', 'to', 'play', 'the', 'guitar']
0.2857142857142857
['ar', 'en', 'en']
['Me', 'gusta', 'cocinar', 'la', 'cena', 'en', 'casa']
0.42857142857142855
['ar']
['Puedes', 'ayudarme', 'con', 'esto']
0.25
['ar', 'ar']
['Gosto', 'de', 'praticar', 'esportes', 'ao', 'ar', 'livre']
0.2857142857142857
['er', 'is', 'ar', 'an']
['Where', 'is', 'the', 'nearest', 'restaurant']
0.8
['er', 'an']
['El', 'perro', 'está', 'jugando']
0.5
['em', 'an']
['Cómo', 'estuvo', 'tu', 'fin', 'de', 'semana']
0.3333333333333333
['en', 'en']
['Que', 'tengas', 'un', 'buen', 'día']
0.4
['is', 'em']
['O', 'filme', 'que', 'assisti', 'ontem', 'foi', 'ótimo']
0.2857142857142857
['an', 'ou', 'is']
['Can', 'you', 'help', 'me', 'with', 'this']
0.5
['en', 'iendo', 'ar', 'an']
['Est

0         1  2          3
0   7.000000  0.500000  0   espanhol
1   4.333333  0.250000  0   espanhol
2   2.333333  0.250000  0     inglês
3   6.500000  0.250000  0   espanhol
4   3.200000  0.650000  0   espanhol
..       ...       ... ..        ...
87  4.500000  0.750000  0  português
88  5.166667  0.583333  0  português
89  3.000000  0.250000  0   espanhol
90  4.500000  0.750000  0  português
91  5.833333  0.916667  0  português

[92 rows x 4 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [106]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [107]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 55.07%
[[ 3  9 11]
 [ 0 14  8]
 [ 1  2 21]]
              precision    recall  f1-score   support

    espanhol       0.75      0.13      0.22        23
      inglês       0.56      0.64      0.60        22
   português       0.53      0.88      0.66        24

    accuracy                           0.55        69
   macro avg       0.61      0.55      0.49        69
weighted avg       0.61      0.55      0.49        69

métricas mais confiáveis
[[0 1 6]
 [0 5 3]
 [0 1 7]]
              precision    recall  f1-score   support

    espanhol       0.00      0.00      0.00         7
      inglês       0.71      0.62      0.67         8
   português       0.44      0.88      0.58         8

    accuracy                           0.52        23
   macro avg       0.38      0.50      0.42        23
weighted avg       0.40      0.52      0.43        23



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
