<a href="https://colab.research.google.com/github/MarogobaCTD/UFPR/blob/main/arq_dados_atividade1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [11]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

In [ ]:
#pip install spacy
import nltk
nltk.download('punkt')
import unicodedata
!python -m spacy download pt_core_news_sm
!python -m spacy download es_core_news_sm
import spacy
import numpy as np
from collections import Counter
import unicodedata

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [12]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['I love to read books.', 'inglês'], ['The cat is sleeping.', 'inglês'], ['Have a great day!', 'inglês'], ['Estou cansado depois de um longo dia de trabalho.', 'português'], ['I enjoy going to the beach.', 'inglês'], ['Me gusta cocinar la cena en casa.', 'espanhol'], ['¿Qué hora es?', 'espanhol'], ['I like to cook dinner at home.', 'inglês'], ['Estou indo para o trabalho agora.', 'português'], ['Estou ansioso para as férias de verão.', 'português'], ['¿Puedes ayudarme con esto?', 'espanhol'], ['Voy al parque todos los días.', 'espanhol'], ['O filme que assisti ontem foi ótimo.', 'português'], ['Vamos fazer um churrasco no final de semana.', 'português'], ['Estou aprendendo a cozinhar pratos novos.', 'português'], ['¿Hablas español?', 'espanhol'], ['Estoy emocionado por el concierto.', 'espanhol'], ['Vou viajar para o exterior nas férias.', 'português'], ['O livro que estou lendo é muito interessante.', 'português'], ['Hola, ¿cómo estás?', 'espanhol'], ['Gosto de ouvir música clássica.

O DataFrame do pandas facilita a visualização.

In [13]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0                               I love to read books.     inglês
1                                The cat is sleeping.     inglês
2                                   Have a great day!     inglês
3   Estou cansado depois de um longo dia de trabalho.  português
4                         I enjoy going to the beach.     inglês
..                                                ...        ...
87                              How was your weekend?     inglês
88                   I'm going to the movies tonight.     inglês
89                            Me encanta leer libros.   espanhol
90                            I enjoy playing soccer.     inglês
91                  Vamos sair para jantar no sábado.  português

[92 rows x 2 columns]

In [23]:
import re

def regra_1(frase):

  # 1. Verificar presença de verbos no presente do indicativo
  verbos_presente = re.findall(r"\w*\[ando|indo|iendo|amos|áis|ão|an|en|mos|em|ém|er|ar|ir]", frase)
  #print(verbos_presente)
  #print(frase.split())
  probabilidade_verbo = len(verbos_presente) / len(frase.split())  # Proporção de verbos no presente
  #print(probabilidade_verbo)

  # 2. Verificar presença de letras ou símbolos
  presenca_es = "".join(["ñ", "¿", "¡", "lo", "la", "el", "un", "mi", "es"]) in frase
  presenca_usa = "".join(["'","I", "the", "The", "is", "it", "you"]) in frase

  # 3. Calcular a probabilidade combinada
  if (probabilidade_verbo > 0.25 and not presenca_es and presenca_usa):
      probabilidade = 0.75  # Alta probabilidade
  elif (probabilidade_verbo > 0.15 and presenca_es):
      probabilidade = 0.5  # Média probabilidade
  else:
      probabilidade = 0.25  # Baixa probabilidade

  return probabilidade_verbo + probabilidade

In [15]:
import re

# Frases de exemplo
frase_ingles = "The quick brown fox jumps over the lazy dog."
frase_portugues = "O rápido lobo marrom pula sobre o cachorro preguiçoso."
frase_espanhol = "El zorro marrón rápido salta sobre el perro perezoso."

# Tokenização com NLTK
def nltk_tokenization(frase):
  tokens = nltk.word_tokenize(frase)
  return tokens

# Tokenização com Expressões Regulares
def regex_tokenization(frase):
  tokens = re.findall(r"\w+", frase)
  return tokens

# Aplicação da tokenização em cada frase
tokens_ingles = nltk_tokenization(frase_ingles)
tokens_portugues = nltk_tokenization(frase_portugues)
tokens_espanhol = nltk_tokenization(frase_espanhol)

# Exibição dos tokens
print("Inglês:", tokens_ingles)
print("Português:", tokens_portugues)
print("Espanhol:", tokens_espanhol)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Inglês: ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', '.']
Português: ['O', 'rápido', 'lobo', 'marrom', 'pula', 'sobre', 'o', 'cachorro', 'preguiçoso', '.']
Espanhol: ['El', 'zorro', 'marrón', 'rápido', 'salta', 'sobre', 'el', 'perro', 'perezoso', '.']


In [17]:
import re

# Função para normalizar texto
def normalize_text(frase):
  # Remover pontuação
  frase = re.sub(r"[^\w\s]", "", frase)
  # Converter para minúsculas
  frase = frase.lower()
  # Remover acentuações
  frase = unicodedata.normalize('NFKD', frase).encode('ascii', 'ignore').decode('utf-8')
  return frase

def word_frequency(frase):
  frequencias = {}
  for palavra in frase.split():
    if palavra in frequencias:
      frequencias[palavra] += 1
    else:
      frequencias[palavra] = 1
  return frequencias

frase = normalize_text("O rápido lobo marrom pula sobre o cachorro preguiçoso.")
frequencias = word_frequency(frase)
print(frequencias)


{'o': 2, 'rapido': 1, 'lobo': 1, 'marrom': 1, 'pula': 1, 'sobre': 1, 'cachorro': 1, 'preguicoso': 1}


In [ ]:

# Carregando os modelos de embedding
nlp_pt = spacy.load("pt_core_news_sm")
nlp_en = spacy.load("en_core_web_sm")
nlp_es = spacy.load("es_core_news_sm")

# Função para gerar embeddings
def generate_embeddings(text, language):
    # Carregando o modelo de embedding correto
    if language == "portuguese":
        nlp = nlp_pt
    elif language == "english":
        nlp = nlp_en
    elif language == "spanish":
        nlp = nlp_es
    else:
        raise ValueError("Invalid language")

    # Tokenização da frase
    doc = nlp(text)
    print(doc)
    # Gerando embeddings para cada token
    embeddings = [token.vector for token in doc]
    return embeddings

# Exemplo de uso
frase_portuguesa = "O rápido lobo marrom pula sobre o cachorro preguiçoso."
frase_inglesa = "The quick brown fox jumps over the lazy dog."
frase_espanhola = "El zorro marrón rápido salta sobre el perro perezoso."

embeddings_portugueses = generate_embeddings(frase_portuguesa, "portuguese")
embeddings_ingleses = generate_embeddings(frase_inglesa, "english")
embeddings_espanholes = generate_embeddings(frase_espanhola, "spanish")

print("Embeddings em português:", embeddings_portugueses)
print("Embeddings em inglês:", embeddings_ingleses)
print("Embeddings em espanhol:", embeddings_espanholes)


In [74]:
import spacy

# Carregando o modelo de linguagem
nlp = spacy.load("pt_core_news_sm")

# Função para calcular a mediana dos N-grams
def ngram_median(sentence, n):
  # Tokenização e pré-processamento
  doc = nlp(sentence.lower())
  tokens = list(doc)

  # Geração de N-grams
  ngrams = []
  for i in range(len(tokens) - n + 1):
    ngrams.append(tuple(tokens[i:i + n]))

  # Cálculo da frequência
  ngram_counts = Counter(ngrams)

  # Ordenação
  sorted_ngrams = sorted(ngram_counts.items(), key=lambda item: item[1])
  #print(sorted_ngrams)
  # Mediana
  mid = len(sorted_ngrams) // 2
  #print(mid)
  #print(sorted_ngrams[mid][1])
  if len(sorted_ngrams) % 2 == 0:
    median = sorted_ngrams[mid][1]
  else:
    median = (sorted_ngrams[mid - 1][1] + sorted_ngrams[mid][1]) / 2

  return median

# Exemplo de uso
#sentence = "O rápido lobo marrom pula sobre o cachorro preguiçoso."
#n = 2  # N-gram de tamanho 2
#median_bigram = ngram_median(sentence, n)
#print("Mediana dos bigrams:", median_bigram)



<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [90]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re
#from unicodedata import category

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)

def extrair_consoantes(frase):
  consoantes = re.findall(r'[¡¿ñÑ]+', frase)
  letras = ''.join(consoantes)
  #print(letras)
  return len(letras)

def conta_palavras_acento(text):
  # Palavras com acento
  accent_regex = re.compile(r"\w+[\xe0-\xff]")
  # Localiza no texto as palavras
  words = re.findall(r"\w+", text)
  count = 0
  for word in words:
    if accent_regex.match(word):
      count += 1
  return count

def mediaPalavrasAcentudas(frase):
  qtdPalavras = len(re.split("\s",frase))
  acentoPalavras = conta_palavras_acento(frase)
  valor = acentoPalavras/qtdPalavras
  #print(valor)
  return valor

# Função para normalizar texto
def normalizarFrase(frase):
  # Remover pontuação
  frase = re.sub(r"[^\w\s]", "", frase)
  # Converter para minúsculas
  frase = frase.lower()
  # Remover acentuações
  frase = unicodedata.normalize('NFKD', frase).encode('ascii', 'ignore').decode('utf-8')
  return frase

def frequenciaPalavras(frase):
  frequencias = {}
  for palavra in frase.split():
    if palavra in frequencias:
      frequencias[palavra] += 1
    else:
      frequencias[palavra] = 1
  #moda = max(frequencias.values(), key=lambda x: x)
  return frequencias


def funcao2(frase):
  return 0
#
#   crie suas funções aqui
#
#

def localizar_numero(frase):
  for caractere in frase:
      if caractere.isdigit():
        return 0
  return 1

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=regra_1(texto)
  caracteristica3=ngram_median(texto, 3)
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[3.2, 0.25, 1.0, 'inglês'], [4.0, 0.25, 1, 'inglês'], [3.25, 0.25, 1, 'inglês'], [4.444444444444445, 0.3611111111111111, 1.0, 'português'], [3.5, 0.41666666666666663, 1, 'inglês'], [3.7142857142857144, 0.6785714285714286, 1.0, 'espanhol'], [3.0, 0.25, 1, 'espanhol'], [3.2857142857142856, 0.39285714285714285, 1.0, 'inglês'], [4.5, 0.5833333333333333, 1, 'português'], [4.428571428571429, 0.8214285714285714, 1.0, 'português'], [5.25, 0.5, 1.0, 'espanhol'], [3.8333333333333335, 0.41666666666666663, 1, 'espanhol'], [4.142857142857143, 0.39285714285714285, 1.0, 'português'], [4.5, 0.75, 1, 'português'], [5.833333333333333, 0.75, 1, 'português'], [6.5, 0.25, 1.0, 'espanhol'], [5.8, 0.65, 1.0, 'espanhol'], [4.428571428571429, 0.6785714285714286, 1.0, 'português'], [4.625, 0.625, 1, 'português'], [4.333333333333333, 0.25, 1, 'espanhol'], [5.2, 0.25, 1.0, 'português'], [3.8333333333333335, 0.5833333333333333, 1.0, 'espanhol'], [4.571428571428571, 0.5357142857142857, 1.0, 'português'], [5.8, 0.8

0         1    2          3
0   3.200000  0.250000  1.0     inglês
1   4.000000  0.250000  1.0     inglês
2   3.250000  0.250000  1.0     inglês
3   4.444444  0.361111  1.0  português
4   3.500000  0.416667  1.0     inglês
..       ...       ...  ...        ...
87  4.250000  0.500000  1.0     inglês
88  3.571429  0.250000  1.0     inglês
89  4.750000  1.000000  1.0   espanhol
90  4.750000  0.750000  1.0     inglês
91  4.500000  0.916667  1.0  português

[92 rows x 4 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [91]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)

Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [92]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 60.87%
[[ 5  8 10]
 [ 0 16  6]
 [ 1  2 21]]
              precision    recall  f1-score   support

    espanhol       0.83      0.22      0.34        23
      inglês       0.62      0.73      0.67        22
   português       0.57      0.88      0.69        24

    accuracy                           0.61        69
   macro avg       0.67      0.61      0.57        69
weighted avg       0.67      0.61      0.57        69

métricas mais confiáveis
[[0 2 5]
 [0 7 1]
 [0 2 6]]
              precision    recall  f1-score   support

    espanhol       0.00      0.00      0.00         7
      inglês       0.64      0.88      0.74         8
   português       0.50      0.75      0.60         8

    accuracy                           0.57        23
   macro avg       0.38      0.54      0.45        23
weighted avg       0.40      0.57      0.46        23



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
